"""Integration net for the HALT alert/journal seam (Brief 9c).

reconcile() deciding "HALT" is worthless if reconcile_and_handle() -- the
wrapper that surfaces it -- silently fails to write the diagnostic dump,
fire the alert, or journal the decision row. That wrapper (and the
dump_halt / alert_stub / record_decision seam it drives) is the only logic
in forgetrader_state.py with zero coverage, and it is the alert path. This
net freezes its behaviour before Week 3 wires real HALTs through it.

Unlike 9b this is I/O, not a pure-fixture net: a tmp scans dir, an
in-memory sqlite journal, and a spy on alert_stub. Standalone script, no
pytest (not installed).

ISOLATION (the load-bearing part):
  dump_halt resolves SCANS_DIR, and reconcile_and_handle resolves
  alert_stub, against the forgetrader_state MODULE namespace at call time.
  So the only correct patch points are `fs.SCANS_DIR` and `fs.alert_stub`.
  Every scenario patches those two, runs, and restores both in a finally
  block. A self-isolation guard in main() proves nothing leaked into the
  real ~/forgetrader/scans/ dir.

ANTI-MIRROR (same rule as 9b): the expected action strings and HALT reasons
below are hand-derived from forgetrader_state.py (lines 138-144, 168-169)
and transcribed verbatim -- never generated by calling reconcile. The
journal-row `detail` is checked by json.loads(detail) == snapshot, not by
string equality, so key ordering is irrelevant.

Style follows tests/test_state_machine.py: a failures list, a per-assertion
message, a counter, sys.exit(1) on any failure, sys.exit(0) clean.
"""

import glob
import json
import os
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import forgetrader_state as fs

# Capture the real scans dir BEFORE any patching, for the self-isolation guard.
_REAL_SCANS = fs.SCANS_DIR


# --------------------------------------------------------------------------- #
# State helper (copied from tests/test_state_machine.py)                      #
# --------------------------------------------------------------------------- #

def _state_at(stage):
    """A schema-complete fresh state with wheel.stage forced to `stage`."""
    s = fs.fresh_flat_state()
    s["wheel"]["stage"] = stage
    return s


# --------------------------------------------------------------------------- #
# Scenario driver                                                            #
# --------------------------------------------------------------------------- #

def run_scenario(stage, snapshot, *, use_conn, run_id):
    """Patch fs.SCANS_DIR + fs.alert_stub, drive reconcile_and_handle once,
    gather every observable, restore both patches. Returns a dict of what the
    seam did. Raised exceptions propagate to the caller (a scenario is allowed
    to assert "no exception").

    sqlite3.Row is subscript-access only (row["stage_from"]), not attribute
    access -- the brief's `row.stage_from` shorthand is spelled that way here.
    """
    tmp_ctx = tempfile.TemporaryDirectory()
    tmp = tmp_ctx.name
    orig_scans = fs.SCANS_DIR
    orig_alert = fs.alert_stub
    calls = []
    conn = None
    try:
        fs.SCANS_DIR = Path(tmp)
        fs.alert_stub = lambda m: calls.append(m)
        if use_conn:
            conn = fs.journal_connect(":memory:")

        state = _state_at(stage)
        ret = fs.reconcile_and_handle(state, snapshot, conn=conn, run_id=run_id)

        dump_files = sorted(glob.glob(os.path.join(tmp, "state_halt_*.txt")))
        dump_text = None
        if len(dump_files) == 1:
            with open(dump_files[0], "r") as f:
                dump_text = f.read()

        decisions = []
        if conn is not None:
            decisions = conn.execute(
                "SELECT stage_from,stage_to,action,detail FROM decisions"
            ).fetchall()

        return {
            "ret": ret,
            "state_in": state,
            "dump_files": dump_files,
            "dump_text": dump_text,
            "decisions": decisions,
            "alert_calls": list(calls),
        }
    finally:
        if conn is not None:
            conn.close()
        fs.SCANS_DIR = orig_scans
        fs.alert_stub = orig_alert
        tmp_ctx.cleanup()


# --------------------------------------------------------------------------- #
# Golden strings - transcribed verbatim from forgetrader_state.py            #
# --------------------------------------------------------------------------- #

# reconcile(), FLAT branch, shares present (lines 141-144):
S1_HALT_ACTION = (
    "HALT:FLAT but broker shows shares=100 put_open=False call_open=False"
)
# the reason substring is that string with the leading "HALT:" stripped
# (reconcile_and_handle line 438: reason = action[len("HALT:"):]):
S1_REASON = "FLAT but broker shows shares=100 put_open=False call_open=False"

# reconcile(), FLAT branch, stable (line 140):
NOOP_FLAT = "noop:FLAT stable"

# reconcile(), CSP_OPEN branch -> apply_trigger("assigned") (lines 168-169,
# 100): f"{stage}->{to_stage} ({trigger})"
ASSIGNED_ACTION = "CSP_OPEN->HOLDING (assigned)"


# --------------------------------------------------------------------------- #
# Assertion helper + counter                                                 #
# --------------------------------------------------------------------------- #

def _check(failures, cond, msg):
    if cond:
        return 1
    failures.append(msg)
    return 0


# --------------------------------------------------------------------------- #
# Scenarios                                                                  #
# --------------------------------------------------------------------------- #

def scenario_1(failures):
    """HALT, with conn+run_id: dump written, alert fired, row journalled."""
    snap = {"shares": 100}
    r = run_scenario("FLAT", snap, use_conn=True, run_id="rid")
    p = 0
    p += _check(failures, len(r["dump_files"]) == 1,
                f"S1: expected exactly 1 dump file, got {len(r['dump_files'])}")
    p += _check(failures,
                r["dump_text"] is not None and S1_REASON in r["dump_text"],
                f"S1: dump text missing reason substring {S1_REASON!r}")
    p += _check(failures, len(r["alert_calls"]) == 1,
                f"S1: expected alert fired once, got {len(r['alert_calls'])}")
    msg = r["alert_calls"][0] if r["alert_calls"] else ""
    p += _check(failures, msg.startswith("HALT "),
                f"S1: alert msg should start with 'HALT ', got {msg!r}")
    p += _check(failures, S1_REASON in msg,
                f"S1: alert msg missing reason substring {S1_REASON!r}: {msg!r}")
    p += _check(failures, "| dump " in msg,
                f"S1: alert msg missing '| dump ' segment: {msg!r}")
    p += _check(failures, len(r["decisions"]) == 1,
                f"S1: expected exactly 1 decisions row, got {len(r['decisions'])}")
    if r["decisions"]:
        row = r["decisions"][0]
        p += _check(failures, row["stage_from"] == "FLAT",
                    f"S1: row.stage_from expected 'FLAT', got {row['stage_from']!r}")
        p += _check(failures, row["stage_to"] == "FLAT",
                    f"S1: row.stage_to expected 'FLAT' (stage unmutated on HALT), "
                    f"got {row['stage_to']!r}")
        p += _check(failures, row["action"] == S1_HALT_ACTION,
                    f"S1: row.action expected {S1_HALT_ACTION!r}, got {row['action']!r}")
        p += _check(failures, json.loads(row["detail"]) == snap,
                    f"S1: json.loads(row.detail) expected {snap!r}, "
                    f"got {json.loads(row['detail'])!r}")
    return p


def scenario_2(failures):
    """noop, with conn+run_id: no dump, no alert, one quiet journal row."""
    snap = {"shares": 0, "put_open": False, "call_open": False}
    r = run_scenario("FLAT", snap, use_conn=True, run_id="rid")
    p = 0
    p += _check(failures, len(r["dump_files"]) == 0,
                f"S2: expected 0 dump files, got {len(r['dump_files'])}")
    p += _check(failures, len(r["alert_calls"]) == 0,
                f"S2: alert should NOT fire, got {r['alert_calls']!r}")
    p += _check(failures, len(r["decisions"]) == 1,
                f"S2: expected exactly 1 decisions row, got {len(r['decisions'])}")
    if r["decisions"]:
        row = r["decisions"][0]
        p += _check(failures, row["stage_from"] == "FLAT",
                    f"S2: row.stage_from expected 'FLAT', got {row['stage_from']!r}")
        p += _check(failures, row["stage_to"] == "FLAT",
                    f"S2: row.stage_to expected 'FLAT', got {row['stage_to']!r}")
        p += _check(failures, row["action"] == NOOP_FLAT,
                    f"S2: row.action expected {NOOP_FLAT!r}, got {row['action']!r}")
        p += _check(failures, json.loads(row["detail"]) == snap,
                    f"S2: json.loads(row.detail) expected {snap!r}, "
                    f"got {json.loads(row['detail'])!r}")
    return p


def scenario_3(failures):
    """transition, with conn+run_id: stage_from BEFORE, stage_to AFTER."""
    snap = {"shares": 100, "put_open": False}
    r = run_scenario("CSP_OPEN", snap, use_conn=True, run_id="rid")
    p = 0
    p += _check(failures, len(r["dump_files"]) == 0,
                f"S3: expected 0 dump files, got {len(r['dump_files'])}")
    p += _check(failures, len(r["alert_calls"]) == 0,
                f"S3: alert should NOT fire, got {r['alert_calls']!r}")
    p += _check(failures, len(r["decisions"]) == 1,
                f"S3: expected exactly 1 decisions row, got {len(r['decisions'])}")
    if r["decisions"]:
        row = r["decisions"][0]
        p += _check(failures, row["stage_from"] == "CSP_OPEN",
                    f"S3: row.stage_from expected 'CSP_OPEN' (captured before "
                    f"transition), got {row['stage_from']!r}")
        p += _check(failures, row["stage_to"] == "HOLDING",
                    f"S3: row.stage_to expected 'HOLDING' (captured after "
                    f"transition), got {row['stage_to']!r}")
        p += _check(failures, row["action"] == ASSIGNED_ACTION,
                    f"S3: row.action expected {ASSIGNED_ACTION!r}, got {row['action']!r}")
        p += _check(failures, json.loads(row["detail"]) == snap,
                    f"S3: json.loads(row.detail) expected {snap!r}, "
                    f"got {json.loads(row['detail'])!r}")
    return p


def scenario_4(failures):
    """HALT, conn=None run_id=None: still dumps + alerts, does not crash,
    returns (state, HALT action)."""
    snap = {"shares": 100}
    exc = None
    r = None
    try:
        r = run_scenario("FLAT", snap, use_conn=False, run_id=None)
    except Exception as e:  # noqa: BLE001 - scenario asserts no exception
        exc = e
    p = 0
    p += _check(failures, exc is None,
                f"S4: reconcile_and_handle raised on the None-journal path: {exc!r}")
    if exc is not None:
        return p
    p += _check(failures, len(r["dump_files"]) == 1,
                f"S4: expected exactly 1 dump file, got {len(r['dump_files'])}")
    p += _check(failures,
                r["dump_text"] is not None and S1_REASON in r["dump_text"],
                f"S4: dump text missing reason substring {S1_REASON!r}")
    p += _check(failures, len(r["alert_calls"]) == 1,
                f"S4: expected alert fired once, got {len(r['alert_calls'])}")
    p += _check(failures, r["decisions"] == [],
                f"S4: no journal write should be attempted, got {r['decisions']!r}")
    ret = r["ret"]
    p += _check(failures, isinstance(ret, tuple) and len(ret) == 2,
                f"S4: return value should be a 2-tuple, got {ret!r}")
    if isinstance(ret, tuple) and len(ret) == 2:
        p += _check(failures, ret[1] == S1_HALT_ACTION,
                    f"S4: return action expected {S1_HALT_ACTION!r}, got {ret[1]!r}")
        p += _check(failures, ret[0] is r["state_in"],
                    "S4: return state should be the (unmutated) input state object")
        p += _check(failures, ret[0]["wheel"]["stage"] == "FLAT",
                    f"S4: return state stage expected 'FLAT', "
                    f"got {ret[0]['wheel']['stage']!r}")
    return p


def scenario_5(failures):
    """noop, conn=None: quiet path stays quiet and crash-free."""
    snap = {"shares": 0, "put_open": False, "call_open": False}
    exc = None
    r = None
    try:
        r = run_scenario("FLAT", snap, use_conn=False, run_id=None)
    except Exception as e:  # noqa: BLE001 - scenario asserts no exception
        exc = e
    p = 0
    p += _check(failures, exc is None,
                f"S5: reconcile_and_handle raised on the quiet None path: {exc!r}")
    if exc is not None:
        return p
    p += _check(failures, len(r["dump_files"]) == 0,
                f"S5: expected 0 dump files, got {len(r['dump_files'])}")
    p += _check(failures, len(r["alert_calls"]) == 0,
                f"S5: alert should NOT fire, got {r['alert_calls']!r}")
    ret = r["ret"]
    p += _check(failures, isinstance(ret, tuple) and len(ret) == 2
                and ret[1] == NOOP_FLAT,
                f"S5: return action expected {NOOP_FLAT!r}, got {ret!r}")
    return p


# --------------------------------------------------------------------------- #
# Runner                                                                     #
# --------------------------------------------------------------------------- #

def _real_halt_files():
    return set(glob.glob(os.path.join(str(_REAL_SCANS), "state_halt_*.txt")))


SCENARIOS = [scenario_1, scenario_2, scenario_3, scenario_4, scenario_5]


def main(argv):
    failures = []

    # Self-isolation guard: snapshot the real scans dir once, up front.
    real_before = _real_halt_files()

    passed = 0
    for fn in SCENARIOS:
        passed += fn(failures)

    # ... and again at the end. Equal => every write hit the tmp dir.
    real_after = _real_halt_files()
    passed += _check(
        failures, real_before == real_after,
        f"ISOLATION: real scans dir gained/lost state_halt files: "
        f"added {sorted(real_after - real_before)} "
        f"removed {sorted(real_before - real_after)}")

    total_asserts = passed + len(failures)

    if failures:
        print("FAIL")
        for f in failures:
            print("  " + f)
        print(f"{len(SCENARIOS)} scenarios + 1 isolation guard, "
              f"{total_asserts} assertions, {passed} passed, "
              f"{len(failures)} failed")
        return 1

    print(f"PASS: {len(SCENARIOS)} scenarios + 1 isolation guard, "
          f"{total_asserts} assertions")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
