"""Consumption net for run.py's propose_csp branch (harness A).

forgetrader/run.py:142-154 -- the `if result.passing_rows:` arm of the
FLAT-stable scan branch -- has never executed. NOK rejects on
spread_too_wide, so no organic passing contract exists; the branch would
otherwise first run under --live, simultaneously with the first live order.
This test drives it with a synthetic passing row, fully offline, so the
branch is proven before --live sits on it.

It asserts what the code does TODAY:
  - scan_action == "propose_csp"
  - the proposal line renders with :.2f strike/collateral and market_open=True
  - exactly one decisions row, its detail byte-identical to the printed line
It does NOT assert "no submission" -- no submission code exists in this
branch yet; that assertion belongs to the --live brief, against the real
submit seam.

OFFLINE. Every live seam is patched on the module namespace run.py resolves
against at call time -- there is no live network and no auth:
  credentials.load_credentials  -> canned ("k","s",True), so no .env read
  fs.read_broker_financials     -> canned FLAT snapshot (zero positions)
  fs.reconcile_and_handle       -> (fresh_flat_state(), "noop:FLAT stable")
  wheel_dryrun.scan_watchlist   -> synthetic ScanResult (the injection point)
The three alpaca clients run.py constructs are inert (alpaca-py client
__init__ issues no request) and are never used -- both of their consumers
(read_broker_financials, scan_watchlist) are patched out.

ISOLATION. fs.STATE_PATH / fs.JOURNAL_PATH are pointed at a mkdtemp dir;
the three fs functions that captured those as *default args* (load_state,
write_state, journal_connect) are thinly wrapped so they re-read the module
attribute at call time. A guard asserts the real
~/forgetrader/{state.json,journal.db} were not touched (mtime + size
unchanged) during the run.

ANTI-MIRROR. EXPECTED_LINE below is hand-derived from
forgetrader/run.py:48-58 and transcribed verbatim -- never produced by
calling _proposal_line.

FAULT-INJECTION. main() runs the (c) rendering assertion through a factored
checker (_assert_line), then re-invokes that checker with a flipped literal
and asserts it reports a failure -- so the net is shown to bite on every
run (it prints "fault-injection: checker correctly bit -> ...").
To watch the whole script exit non-zero naming the case, hand-edit
EXPECTED_LINE below (change its "strike=12.00" to "strike=99.00"), run

    .venv/bin/python tests/test_propose_csp.py; echo "exit=$?"

-- it prints FAIL, "(c) rendering: ...", "1 failed", exit=1 -- then change
EXPECTED_LINE back. (A blanket sed is deliberately not given: the token
occurs in several places here, including this docstring.)

Style follows tests/test_reconcile_handle.py: a failures list, a
per-assertion message, a counter, sys.exit(1) + failing-case name on any
failure, sys.exit(0) when all pass. No pytest.
"""

import contextlib
import io
import os
import sqlite3
import sys
import tempfile
from collections import Counter
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import credentials
import forgetrader_state as fs
import wheel_dryrun
from forgetrader.run import run

# Real state/journal paths captured BEFORE any patching, for the guard.
_REAL_STATE = Path(fs.STATE_PATH)
_REAL_JOURNAL = Path(fs.JOURNAL_PATH)


# --------------------------------------------------------------------------- #
# Anti-mirror golden - hand-derived from forgetrader/run.py:48-58            #
# --------------------------------------------------------------------------- #
# _proposal_line(ROW, is_open=True), field by field:
#   f"propose_csp {row['underlying_symbol']} "
#   f"strike={row['strike']:.2f} right=P expiry={row['expiration_date']} "
#   f"bid={row['bid']} oi={row['open_interest']} "
#   f"annualized_yield_pct={row['annualized_yield_pct']} "
#   f"collateral={row['collateral']:.2f} market_open={is_open}"
# Transcribed by hand from that source - NOT generated by calling
# _proposal_line. Flip "strike=12.00" here to see the net exit non-zero
# (see FAULT-INJECTION in the module docstring).
EXPECTED_LINE = (
    "propose_csp TEST strike=12.00 right=P expiry=2026-10-16 "
    "bid=0.25 oi=500 annualized_yield_pct=18.0 collateral=1200.00 "
    "market_open=True"
)


# --------------------------------------------------------------------------- #
# Synthetic fixtures                                                         #
# --------------------------------------------------------------------------- #

# fresh_flat_state(equity=.., cash=.., options_buying_power=.., positions=..)
# reads these four by key (run.py:111-114); build_flat_snapshot's
# zero-position guard reads positions and passes legitimately on [].
CANNED_FLAT_FINANCIALS = {
    "equity": 1300.0,
    "cash": 1300.0,
    "options_buying_power": 1300.0,
    "positions": [],
}

# keys mirror wheel_dryrun.py:425 row-construction + the 7 keys read by
# run.py `_proposal_line` (run.py:48-58). strike and collateral are floats:
# they hit :.2f (a str there is a ValueError), and asserting that formatting
# survives is part of the point.
ROW = {
    "underlying_symbol": "TEST",
    "strike": 12.0,
    "expiration_date": "2026-10-16",
    "bid": 0.25,
    "open_interest": 500,
    "annualized_yield_pct": 18.0,
    "collateral": 1200.0,
}


class _ClockStub:
    """getattr(result.clock, "is_open", None) is all run.py:141 reads."""

    is_open = True


def _synthetic_scan_result():
    """Construct ScanResult with EVERY kwarg from wheel_dryrun.py:201-206.
    The signature is keyword-only, so a missing kwarg is a TypeError -- that
    is fine, it forces this fixture to stay faithful to the real shape.
    Everything but clock + passing_rows is empty."""
    return wheel_dryrun.ScanResult(
        trace_lines=[],
        passing_rows=[ROW],            # run.py takes [0]; OI-desc sorted in prod
        all_rows=[],
        reject_tally=Counter(),
        per_name=[],
        earnings_by_ticker={},
        coll={},
        approved=[],
        wl_rejected=[],
        wl_warnings=[],
        clock=_ClockStub(),
        chain_fetch_errors=[],
        dte_min=0,
        dte_max=0,
        exp_gte="",
        exp_lte="",
        min_underlying_price=0,
    )


# --------------------------------------------------------------------------- #
# Driver: patch every seam, redirect state/journal to a tmpdir, run run()    #
# --------------------------------------------------------------------------- #

def _drive():
    """Returns (ret, stdout_text, decisions_rows, tmp_journal_path). Restores
    every patch in a finally block."""
    tmp = tempfile.mkdtemp(prefix="propose_csp_")
    tmp_state = Path(tmp) / "state.json"
    tmp_journal = Path(tmp) / "journal.db"

    orig = {
        "STATE_PATH": fs.STATE_PATH,
        "JOURNAL_PATH": fs.JOURNAL_PATH,
        "load_state": fs.load_state,
        "write_state": fs.write_state,
        "journal_connect": fs.journal_connect,
        "read_broker_financials": fs.read_broker_financials,
        "reconcile_and_handle": fs.reconcile_and_handle,
    }
    orig_load_credentials = credentials.load_credentials
    orig_scan_watchlist = wheel_dryrun.scan_watchlist

    _orig_load_state = orig["load_state"]
    _orig_write_state = orig["write_state"]
    _orig_journal_connect = orig["journal_connect"]

    buf = io.StringIO()
    try:
        # --- path redirection. The module attribute is the source of truth
        #     (test_reconcile_handle idiom); these three fns captured it as a
        #     def-time default arg, so wrap them to re-read it at call time.
        fs.STATE_PATH = tmp_state
        fs.JOURNAL_PATH = tmp_journal
        fs.load_state = lambda path=None: _orig_load_state(path or fs.STATE_PATH)
        fs.write_state = (
            lambda state, path=None: _orig_write_state(state, path or fs.STATE_PATH)
        )
        fs.journal_connect = (
            lambda path=None: _orig_journal_connect(path or fs.JOURNAL_PATH)
        )

        # --- live seams (harness A: branch runs in place, nothing extracted)
        credentials.load_credentials = lambda: ("k", "s", True)
        fs.read_broker_financials = (
            lambda trading_client=None: dict(CANNED_FLAT_FINANCIALS)
        )
        fs.reconcile_and_handle = (
            lambda state, snap, conn=None, run_id=None: (
                fs.fresh_flat_state(), "noop:FLAT stable"
            )
        )
        wheel_dryrun.scan_watchlist = lambda *a, **k: _synthetic_scan_result()

        with contextlib.redirect_stdout(buf):
            ret = run(dry_run=True)

        conn = sqlite3.connect(str(tmp_journal))
        conn.row_factory = sqlite3.Row
        rows = conn.execute(
            "SELECT stage_from, stage_to, action, detail FROM decisions"
        ).fetchall()
        conn.close()
        return ret, buf.getvalue(), rows, tmp_journal
    finally:
        fs.STATE_PATH = orig["STATE_PATH"]
        fs.JOURNAL_PATH = orig["JOURNAL_PATH"]
        fs.load_state = orig["load_state"]
        fs.write_state = orig["write_state"]
        fs.journal_connect = orig["journal_connect"]
        fs.read_broker_financials = orig["read_broker_financials"]
        fs.reconcile_and_handle = orig["reconcile_and_handle"]
        credentials.load_credentials = orig_load_credentials
        wheel_dryrun.scan_watchlist = orig_scan_watchlist


# --------------------------------------------------------------------------- #
# Assertion helpers                                                          #
# --------------------------------------------------------------------------- #

def _check(failures, cond, msg):
    if cond:
        return 1
    failures.append(msg)
    return 0


def _assert_line(detail, expected, label):
    """The (c) rendering assertion, factored so fault-injection can invoke it
    with a mutated `expected` and observe it fail. Returns a list of failure
    messages (empty == passed)."""
    fails = []
    _check(fails, detail == expected,
           f"{label}: journal detail {detail!r} != expected {expected!r}")
    return fails


# --------------------------------------------------------------------------- #
# Runner                                                                     #
# --------------------------------------------------------------------------- #

def _fingerprint(p):
    if not p.exists():
        return None
    st = p.stat()
    return (st.st_mtime_ns, st.st_size)


def main():
    failures = []
    passed = 0

    # Self-isolation guard: fingerprint the real state/journal BEFORE the run.
    real_state_before = _fingerprint(_REAL_STATE)
    real_journal_before = _fingerprint(_REAL_JOURNAL)

    ret, out, rows, tmp_journal = _drive()

    real_state_after = _fingerprint(_REAL_STATE)
    real_journal_after = _fingerprint(_REAL_JOURNAL)

    # (a) noop path returns 0
    passed += _check(
        failures, ret == 0,
        f"(a) run(dry_run=True) should return 0 on the noop path, got {ret!r}")

    # (b) stdout carries the rendered proposal line. Substring checks only -
    #     EXPECTED_LINE is anti-mirror, never built by calling _proposal_line.
    out_lines = [ln.strip() for ln in out.splitlines()]
    prop_lines = [
        ln for ln in out_lines
        if ln.startswith("propose_csp TEST strike=12.00")
    ]
    passed += _check(
        failures, len(prop_lines) == 1,
        f"(b) expected exactly one stdout line beginning "
        f"'propose_csp TEST strike=12.00', got {prop_lines!r}\n"
        f"--- full stdout ---\n{out}")
    if prop_lines:
        pl = prop_lines[0]
        passed += _check(
            failures, "collateral=1200.00" in pl,
            f"(b) proposal line missing 'collateral=1200.00': {pl!r}")
        passed += _check(
            failures, "market_open=True" in pl,
            f"(b) proposal line missing 'market_open=True': {pl!r}")

    # (c) exactly one decisions row; propose_csp; FLAT->FLAT; detail == the
    #     printed proposal line (the printed==journaled seam).
    passed += _check(
        failures, len(rows) == 1,
        f"(c) expected exactly 1 decisions row, got {len(rows)}: "
        f"{[tuple(r) for r in rows]}")
    if len(rows) == 1:
        r = rows[0]
        passed += _check(
            failures, r["action"] == "propose_csp",
            f"(c) row.action expected 'propose_csp', got {r['action']!r}")
        passed += _check(
            failures, r["stage_from"] == fs.FLAT,
            f"(c) row.stage_from expected {fs.FLAT!r}, got {r['stage_from']!r}")
        passed += _check(
            failures, r["stage_to"] == fs.FLAT,
            f"(c) row.stage_to expected {fs.FLAT!r}, got {r['stage_to']!r}")
        # run.py:155 prints `f"  {detail}"` - the 2-space indent is the only
        # leading whitespace and _proposal_line's output has none of its own,
        # so the stripped stdout line is byte-identical to the journal detail.
        passed += _check(
            failures, bool(prop_lines) and r["detail"] == prop_lines[0],
            "(c) journal detail != printed proposal line\n"
            f"  journal : {r['detail']!r}\n"
            f"  printed : {(prop_lines[0] if prop_lines else None)!r}")
        # ...and the rendering itself is byte-exact against the hand-derived
        # golden. Factored through _assert_line so fault-injection can reuse it.
        render_fails = _assert_line(r["detail"], EXPECTED_LINE, "(c) rendering")
        passed += _check(failures, not render_fails,
                         render_fails[0] if render_fails else "(c) rendering ok")

        # --- Fault-injection proof (9b discipline): feed the SAME checker a
        #     flipped literal and confirm it reports a failure. If it does not,
        #     the regression net is asleep.
        injected = _assert_line(
            r["detail"],
            EXPECTED_LINE.replace("strike=12.00", "strike=99.00"),
            "(fault)")
        passed += _check(
            failures, len(injected) == 1,
            "FAULT-INJECTION: the rendering checker did NOT fail when fed "
            "strike=99.00 - the regression net is not biting")
        if injected:
            print(f"  fault-injection: checker correctly bit -> {injected[0]}")

    # Self-isolation guard: the real state/journal must be byte-for-byte
    # untouched (no write leaked out of the tmpdir).
    passed += _check(
        failures, real_state_before == real_state_after,
        f"ISOLATION: real {_REAL_STATE} changed during the run "
        f"(before={real_state_before}, after={real_state_after})")
    passed += _check(
        failures, real_journal_before == real_journal_after,
        f"ISOLATION: real {_REAL_JOURNAL} changed during the run "
        f"(before={real_journal_before}, after={real_journal_after})")
    # ...and positive proof the decision row DID land in the tmp journal.
    passed += _check(
        failures, tmp_journal.exists(),
        f"ISOLATION: expected a journal at {tmp_journal}, none was written")

    total = passed + len(failures)
    if failures:
        print("FAIL")
        for f in failures:
            print("  " + f)
        print(f"{total} assertions, {passed} passed, {len(failures)} failed")
        return 1
    print(f"PASS: {total} assertions "
          f"(propose_csp branch: action + :.2f rendering + printed==journaled "
          f"seam + isolation + fault-injection bite)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
