"""Golden-fixture regression net for the wheel state machine (Brief 9b).

forgetrader_state.py holds the whole wheel state machine: the
LEGAL_TRANSITIONS table + apply_trigger() (intent-driven), and reconcile()
(broker-driven). This net freezes every current, human-verified output so a
later edit that silently breaks a transition, a noop, or a HALT is caught.
It goes UNDER assignment-detection and CC-flip next, so it is written to
catch CURRENT behaviour, not just future drift.

The expected action strings and expected resulting stages below are ground
truth, hand-derived from the source (forgetrader_state.py lines 56-216) and
transcribed verbatim. They are NOT generated by calling apply_trigger /
reconcile and capturing output -- a net built from the code under test
proves nothing. If an assertion fails, that is a signal to STOP and report
the mismatch, never to edit the golden or the source to match.

`import forgetrader_state as fs` at module scope is safe: the only
SDK-touching code (read_broker_financials) imports alpaca-py locally. This
net never calls read_broker_financials, the CLI, or touches
state.json / journal.db. Pure in-memory only.

Style follows tests/test_gates.py: plain comparisons (no pytest, not
installed), fixture lists, a loop, a per-assertion failure message, a
pass/fail counter, sys.exit(1) on any failure, sys.exit(0) clean.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import forgetrader_state as fs


# --------------------------------------------------------------------------- #
# State helper                                                               #
# --------------------------------------------------------------------------- #

def _state_at(stage):
    """A schema-complete fresh state with wheel.stage forced to `stage`.

    Built through the real schema (fresh_flat_state), then the stage is set
    directly so illegal / unknown stages ("GARBAGE") can be exercised too.
    generated_at / last_run.ts are nondeterministic and never asserted on.
    """
    s = fs.fresh_flat_state()
    s["wheel"]["stage"] = stage
    return s


# --------------------------------------------------------------------------- #
# FAMILY A - apply_trigger  (pins LEGAL_TRANSITIONS directly)                 #
# --------------------------------------------------------------------------- #
#
# Each row: (label, from_stage, trigger, expected_action, expected_to, legal)
#   legal=True  -> new_state is a deep copy, wheel.stage == expected_to,
#                  caller's stage UNCHANGED, new_state IS NOT the input.
#   legal=False -> action == expected_action (a "HALT:..." string),
#                  wheel.stage UNCHANGED (== from_stage == expected_to),
#                  new_state IS the input object (no copy on the illegal path).
#
# HALT string is  f"HALT:no legal transition from {stage} on trigger {trigger!r}"
# so the trigger is repr()'d -> wrapped in single quotes.

FAMILY_A = [
    # -- 10 LEGAL --------------------------------------------------------
    ("A-legal-FLAT-submit_csp",
     "FLAT", "submit_csp",
     "FLAT->CSP_PENDING (submit_csp)", "CSP_PENDING", True),
    ("A-legal-CSP_PENDING-fill",
     "CSP_PENDING", "fill",
     "CSP_PENDING->CSP_OPEN (fill)", "CSP_OPEN", True),
    ("A-legal-CSP_PENDING-reject_or_cancel",
     "CSP_PENDING", "reject_or_cancel",
     "CSP_PENDING->FLAT (reject_or_cancel)", "FLAT", True),
    ("A-legal-CSP_OPEN-assigned",
     "CSP_OPEN", "assigned",
     "CSP_OPEN->HOLDING (assigned)", "HOLDING", True),
    ("A-legal-CSP_OPEN-expired_worthless",
     "CSP_OPEN", "expired_worthless",
     "CSP_OPEN->FLAT (expired_worthless)", "FLAT", True),
    ("A-legal-HOLDING-submit_cc",
     "HOLDING", "submit_cc",
     "HOLDING->CC_PENDING (submit_cc)", "CC_PENDING", True),
    ("A-legal-CC_PENDING-fill",
     "CC_PENDING", "fill",
     "CC_PENDING->CC_OPEN (fill)", "CC_OPEN", True),
    ("A-legal-CC_PENDING-reject_or_cancel",
     "CC_PENDING", "reject_or_cancel",
     "CC_PENDING->HOLDING (reject_or_cancel)", "HOLDING", True),
    ("A-legal-CC_OPEN-called_away",
     "CC_OPEN", "called_away",
     "CC_OPEN->FLAT (called_away)", "FLAT", True),
    ("A-legal-CC_OPEN-cc_expired_worthless",
     "CC_OPEN", "cc_expired_worthless",
     "CC_OPEN->HOLDING (cc_expired_worthless)", "HOLDING", True),

    # -- 4 ILLEGAL ----------------------------------------------------------
    ("A-illegal-FLAT-fill",
     "FLAT", "fill",
     "HALT:no legal transition from FLAT on trigger 'fill'", "FLAT", False),
    ("A-illegal-CSP_OPEN-submit_csp",
     "CSP_OPEN", "submit_csp",
     "HALT:no legal transition from CSP_OPEN on trigger 'submit_csp'",
     "CSP_OPEN", False),
    ("A-illegal-HOLDING-assigned",
     "HOLDING", "assigned",
     "HALT:no legal transition from HOLDING on trigger 'assigned'",
     "HOLDING", False),
    ("A-illegal-CC_OPEN-submit_csp",
     "CC_OPEN", "submit_csp",
     "HALT:no legal transition from CC_OPEN on trigger 'submit_csp'",
     "CC_OPEN", False),
]


# --------------------------------------------------------------------------- #
# FAMILY B - reconcile  (broker-driven)                                      #
# --------------------------------------------------------------------------- #
#
# Each row: (label, stage, broker_snapshot, expected_action, expected_stage, kind)
#   kind == "transition" -> action exact, new_state["wheel"]["stage"] ==
#                           expected_stage, caller stage UNMUTATED,
#                           new_state IS NOT the input (reconcile hands back
#                           apply_trigger's deep copy).
#   kind == "noop"       -> action exact, new_state IS the input object,
#                           stage unchanged (== stage == expected_stage).
#   kind == "halt"       -> action exact ("HALT:..."), new_state IS the input
#                           object, caller stage UNMUTATED.
#
# broker_snapshot keys: shares (int), put_open (bool), call_open (bool),
# pending_order_status (str|None). Keys are omitted only where the fixture is
# explicitly testing their absence.

FAMILY_B = [
    # -- TRANSITIONS ------------------------------------------------------
    ("B-tr-CSP_PENDING-filled",
     "CSP_PENDING", {"shares": 0, "pending_order_status": "filled"},
     "CSP_PENDING->CSP_OPEN (fill)", "CSP_OPEN", "transition"),
    ("B-tr-CSP_PENDING-put_open-path",
     "CSP_PENDING",
     {"shares": 0, "put_open": True, "pending_order_status": None},
     "CSP_PENDING->CSP_OPEN (fill)", "CSP_OPEN", "transition"),
    ("B-tr-CSP_PENDING-canceled",
     "CSP_PENDING", {"shares": 0, "pending_order_status": "canceled"},
     "CSP_PENDING->FLAT (reject_or_cancel)", "FLAT", "transition"),
    ("B-tr-CSP_OPEN-assigned",
     "CSP_OPEN", {"shares": 100, "put_open": False},
     "CSP_OPEN->HOLDING (assigned)", "HOLDING", "transition"),
    ("B-tr-CSP_OPEN-expired_worthless",
     "CSP_OPEN", {"shares": 0, "put_open": False},
     "CSP_OPEN->FLAT (expired_worthless)", "FLAT", "transition"),
    ("B-tr-CC_PENDING-filled",
     "CC_PENDING", {"shares": 100, "pending_order_status": "filled"},
     "CC_PENDING->CC_OPEN (fill)", "CC_OPEN", "transition"),
    ("B-tr-CC_PENDING-rejected",
     "CC_PENDING", {"shares": 100, "pending_order_status": "rejected"},
     "CC_PENDING->HOLDING (reject_or_cancel)", "HOLDING", "transition"),
    ("B-tr-CC_OPEN-called_away",
     "CC_OPEN", {"shares": 0, "call_open": False},
     "CC_OPEN->FLAT (called_away)", "FLAT", "transition"),
    ("B-tr-CC_OPEN-cc_expired_worthless",
     "CC_OPEN", {"shares": 100, "call_open": False},
     "CC_OPEN->HOLDING (cc_expired_worthless)", "HOLDING", "transition"),
    ("B-tr-CC_PENDING-call_open-path",
     "CC_PENDING",
     {"shares": 100, "call_open": True, "pending_order_status": None},
     "CC_PENDING->CC_OPEN (fill)", "CC_OPEN", "transition"),

    # -- NOOPS ------------------------------------------------------------
    ("B-noop-FLAT-stable",
     "FLAT", {"shares": 0, "put_open": False, "call_open": False},
     "noop:FLAT stable", "FLAT", "noop"),
    ("B-noop-CSP_PENDING-new",
     "CSP_PENDING", {"shares": 0, "pending_order_status": "new"},
     "noop:CSP_PENDING awaiting fill", "CSP_PENDING", "noop"),
    ("B-noop-CSP_PENDING-none-status",
     "CSP_PENDING", {"shares": 0, "pending_order_status": None},
     "noop:CSP_PENDING awaiting fill", "CSP_PENDING", "noop"),
    ("B-noop-CSP_OPEN-stable",
     "CSP_OPEN", {"shares": 0, "put_open": True},
     "noop:CSP_OPEN stable", "CSP_OPEN", "noop"),
    ("B-noop-HOLDING-stable",
     "HOLDING", {"shares": 100, "put_open": False, "call_open": False},
     "noop:HOLDING stable", "HOLDING", "noop"),
    ("B-noop-CC_PENDING-accepted",
     "CC_PENDING", {"shares": 100, "pending_order_status": "accepted"},
     "noop:CC_PENDING awaiting fill", "CC_PENDING", "noop"),
    ("B-noop-CC_OPEN-stable",
     "CC_OPEN", {"shares": 100, "call_open": True},
     "noop:CC_OPEN stable", "CC_OPEN", "noop"),

    # -- HALTS: prechecks run BEFORE the stage branch ------------------
    ("B-halt-precheck-missing-shares",
     "CSP_OPEN", {},
     "HALT:broker_snapshot missing required key 'shares'", "CSP_OPEN", "halt"),
    ("B-halt-precheck-shares-negative",
     "FLAT", {"shares": -1},
     "HALT:broker_snapshot['shares'] not a non-negative int: -1",
     "FLAT", "halt"),
    ("B-halt-precheck-shares-bool",
     "FLAT", {"shares": True},
     "HALT:broker_snapshot['shares'] not a non-negative int: True",
     "FLAT", "halt"),
    ("B-halt-precheck-shares-float",
     "FLAT", {"shares": 100.0},
     "HALT:broker_snapshot['shares'] not a non-negative int: 100.0",
     "FLAT", "halt"),

    # -- HALTS: stage-specific -------------------------------------------
    ("B-halt-FLAT-shares-present",
     "FLAT", {"shares": 100},
     "HALT:FLAT but broker shows shares=100 put_open=False call_open=False",
     "FLAT", "halt"),
    ("B-halt-CSP_PENDING-filling-shares",
     "CSP_PENDING", {"shares": 100, "pending_order_status": "filled"},
     "HALT:CSP_PENDING filling but broker shows shares=100",
     "CSP_PENDING", "halt"),
    ("B-halt-CSP_PENDING-canceled-shares",
     "CSP_PENDING", {"shares": 100, "pending_order_status": "canceled"},
     "HALT:CSP_PENDING order canceled but broker shows shares=100 "
     "put_open=False",
     "CSP_PENDING", "halt"),
    ("B-halt-CSP_PENDING-unknown-status",
     "CSP_PENDING", {"shares": 0, "pending_order_status": "weird_status"},
     "HALT:CSP_PENDING unknown pending_order_status 'weird_status'",
     "CSP_PENDING", "halt"),
    ("B-halt-CSP_OPEN-put-open-shares",
     "CSP_OPEN", {"shares": 100, "put_open": True},
     "HALT:CSP_OPEN put still open but broker shows shares=100",
     "CSP_OPEN", "halt"),
    ("B-halt-CSP_OPEN-partial-lot",
     "CSP_OPEN", {"shares": 50, "put_open": False},
     "HALT:CSP_OPEN put gone and shares=50 is neither a 100-share "
     "assignment lot nor flat",
     "CSP_OPEN", "halt"),
    ("B-halt-HOLDING-no-shares",
     "HOLDING", {"shares": 0},
     "HALT:HOLDING but broker shows shares=0 put_open=False call_open=False",
     "HOLDING", "halt"),
    ("B-halt-CC_PENDING-filling-shares",
     "CC_PENDING", {"shares": 0, "pending_order_status": "filled"},
     "HALT:CC_PENDING filling but broker shows shares=0",
     "CC_PENDING", "halt"),
    ("B-halt-CC_PENDING-canceled-shares",
     "CC_PENDING", {"shares": 0, "pending_order_status": "canceled"},
     "HALT:CC_PENDING order canceled but broker shows shares=0 "
     "call_open=False",
     "CC_PENDING", "halt"),
    ("B-halt-CC_PENDING-unknown-status",
     "CC_PENDING", {"shares": 100, "pending_order_status": "weird"},
     "HALT:CC_PENDING unknown pending_order_status 'weird'",
     "CC_PENDING", "halt"),
    ("B-halt-CC_OPEN-call-open-shares",
     "CC_OPEN", {"shares": 0, "call_open": True},
     "HALT:CC_OPEN call still open but broker shows shares=0",
     "CC_OPEN", "halt"),
    ("B-halt-CC_OPEN-partial-lot",
     "CC_OPEN", {"shares": 50, "call_open": False},
     "HALT:CC_OPEN call gone and shares=50 is neither flat (called away) "
     "nor a full 100-share lot (expiry)",
     "CC_OPEN", "halt"),
    ("B-halt-unknown-stage",
     "GARBAGE", {"shares": 0},
     "HALT:unknown stage 'GARBAGE'", "GARBAGE", "halt"),
]


# --------------------------------------------------------------------------- #
# Runner                                                                     #
# --------------------------------------------------------------------------- #

def _check(failures, cond, msg):
    """Record `msg` in `failures` unless `cond`. Returns 1 on pass, 0 on fail
    so the caller can total an assertion count."""
    if cond:
        return 1
    failures.append(msg)
    return 0


def run_family_a(failures):
    passed = 0
    for label, from_stage, trigger, exp_action, exp_to, legal in FAMILY_A:
        state = _state_at(from_stage)
        new_state, action = fs.apply_trigger(state, trigger)

        passed += _check(
            failures, action == exp_action,
            f"{label}: action expected {exp_action!r} got {action!r}")
        passed += _check(
            failures, new_state["wheel"]["stage"] == exp_to,
            f"{label}: new stage expected {exp_to!r} got "
            f"{new_state['wheel']['stage']!r}")
        passed += _check(
            failures, state["wheel"]["stage"] == from_stage,
            f"{label}: caller stage mutated to "
            f"{state['wheel']['stage']!r} (expected {from_stage!r})")

        if legal:
            passed += _check(
                failures, new_state is not state,
                f"{label}: legal path must deep-copy, "
                f"new_state IS the input object")
        else:
            passed += _check(
                failures, new_state is state,
                f"{label}: illegal path must return the input object, "
                f"got a copy")
    return passed


def run_family_b(failures):
    passed = 0
    for label, stage, snapshot, exp_action, exp_stage, kind in FAMILY_B:
        state = _state_at(stage)
        new_state, action = fs.reconcile(state, snapshot)

        passed += _check(
            failures, action == exp_action,
            f"{label}: action expected {exp_action!r} got {action!r}")
        passed += _check(
            failures, new_state["wheel"]["stage"] == exp_stage,
            f"{label}: resulting stage expected {exp_stage!r} got "
            f"{new_state['wheel']['stage']!r}")
        passed += _check(
            failures, state["wheel"]["stage"] == stage,
            f"{label}: caller stage mutated to "
            f"{state['wheel']['stage']!r} (expected {stage!r})")

        if kind == "transition":
            passed += _check(
                failures, new_state is not state,
                f"{label}: transition must hand back a new state object, "
                f"got the input")
        else:  # noop / halt
            passed += _check(
                failures, new_state is state,
                f"{label}: {kind} must return the input state object, "
                f"got a copy")
    return passed


def main(argv):
    failures = []
    passed = 0
    passed += run_family_a(failures)
    passed += run_family_b(failures)

    total_fixtures = len(FAMILY_A) + len(FAMILY_B)
    total_asserts = passed + len(failures)

    if failures:
        print("FAIL")
        for f in failures:
            print("  " + f)
        print(f"{total_fixtures} fixtures, {total_asserts} assertions, "
              f"{passed} passed, {len(failures)} failed")
        return 1

    print(f"PASS: {total_fixtures} fixtures "
          f"({len(FAMILY_A)} apply_trigger + {len(FAMILY_B)} reconcile), "
          f"{total_asserts} assertions")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
